"""create links table

Revision ID: 469139943c7f
Revises: c81e7e299463
Create Date: 2025-08-27 17:25:54.450267

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "469139943c7f"
down_revision: str | Sequence[str] | None = "c81e7e299463"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
