"""create links table

Revision ID: c81e7e299463
Revises: bb678cb2bb05
Create Date: 2025-08-27 16:55:16.556797

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c81e7e299463"
down_revision: str | Sequence[str] | None = "bb678cb2bb05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("long_url", sa.String(length=2048), nullable=False),
        sa.Column("short_url", sa.String(length=512), nullable=False),
        sa.Column("service", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("copy_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.create_index("ix_links_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_links_long_like", ["long_url"], unique=False)
        batch_op.create_index("ix_links_service", ["service"], unique=False)
        batch_op.create_index("ix_links_short_like", ["short_url"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.drop_index("ix_links_short_like")
        batch_op.drop_index("ix_links_service")
        batch_op.drop_index("ix_links_long_like")
        batch_op.drop_index("ix_links_created_at")

    op.drop_table("links")
    # ### end Alembic commands ###
